apiVersion: apps/v1
kind: Deployment
metadata:
  name: domashka13
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: your-app-image:latest
        ports:
          - containerPort: 8080
        ports:
        - containerPort: 80
-----
apiVersion: v1
kind: domashka13
metadata:
  name: mysql-domashka13
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bWF4MTIzNA0K
  MYSQL_USER: ZG9tYXNoa2ExM3VzZXI=
  MYSQL_PASSWORD: ZG9tYXNoa2ExM1BBU1NXT1JE
-------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        envFrom:
        - secretRef:
            name: mysql-secrets
        ports:
        - containerPort: 3306
-----
apiVersion: v1
kind: domashka13
metadata:
  name: my-app-domashka13
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: domashka13
metadata:
  name: mysql-db-domashka13
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306